// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXSXLqjapjeTUKA5F195RkiNoFGEYqW-Y',
    appId: '1:823803436350:web:373274e1adef8ee38c206f',
    messagingSenderId: '823803436350',
    projectId: 'ecommerce-85b67',
    authDomain: 'ecommerce-85b67.firebaseapp.com',
    storageBucket: 'ecommerce-85b67.appspot.com',
    measurementId: 'G-LF78L1Q737',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALbecwANVqIB7zmrH0BFcqTOBcZo6NXaM',
    appId: '1:823803436350:android:5c312d01cc0cfed98c206f',
    messagingSenderId: '823803436350',
    projectId: 'ecommerce-85b67',
    storageBucket: 'ecommerce-85b67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDReeh9yJxJB9Rm8edqGCQWwdLlapbfANg',
    appId: '1:823803436350:ios:dc98281a61addde38c206f',
    messagingSenderId: '823803436350',
    projectId: 'ecommerce-85b67',
    storageBucket: 'ecommerce-85b67.appspot.com',
    iosClientId: '823803436350-nsohtlvk41229kk0j6a7hvnen650vh9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDReeh9yJxJB9Rm8edqGCQWwdLlapbfANg',
    appId: '1:823803436350:ios:de1859deee1992a78c206f',
    messagingSenderId: '823803436350',
    projectId: 'ecommerce-85b67',
    storageBucket: 'ecommerce-85b67.appspot.com',
    iosClientId: '823803436350-6hs9tv7tmvef2ogthiej8r468nh2qg74.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
